/**
 * Shared (client + server) types and formatters for transcripts.
 *
 * Do NOT put anything here that touches the AssemblyAI SDK or server-only
 * state — this file is imported from client components.
 */

/** A row from our `transcripts` table, as returned by /api/transcripts. */
export interface StoredTranscript {
  id: number;
  user_id: string;
  assemblyai_id: string;
  original_filename: string | null;
  status: string;
  created_at: string;
  completed_at: string | null;
  duration: number | null;
  speaker_count: number | null;
  language_code: string | null;
  title: string | null;
  description: string | null;
  last_accessed: string;
  source: 'uploaded' | 'imported';
  /** present only when source = 'imported'; the full AAI payload frozen at import time */
  imported_content: TranscriptResponse | null;
  /** cached AAI audio_url at the time of upload/import (may stop working over time) */
  audio_url: string | null;
  /** server-local fallback audio file (set during import after we download the bytes) */
  local_audio_path: string | null;
  /** Drive file ID of the source recording (Google Meet import) — dedupe key */
  drive_file_id: string | null;
  /** source-meeting metadata for Google Meet imports */
  gmeet_context: GmeetContext | null;
  /** when the meeting actually happened (vs created_at = upload time); from
   * the linked calendar event/conference, or set by hand */
  recorded_at: string | null;
  /** AI meeting notes generated by headless Claude on the server (markdown) */
  auto_notes: string | null;
  /** AI-suggested topical segments, ordered by start_ms */
  auto_segments: TranscriptSegment[] | null;
  /** null = never attempted; 'running' | 'completed' | 'error' */
  auto_notes_status: string | null;
  auto_notes_error: string | null;
  auto_notes_at: string | null;
  /** Detailed wiki-style AI report (markdown with frame images, t: links) */
  auto_report: string | null;
  auto_report_status: string | null;
  auto_report_error: string | null;
  auto_report_at: string | null;
  /** Speaker-identification AI pass (runs at completion, before notes).
   * null = never attempted; 'running' | 'completed' | 'error' */
  speaker_id_status: string | null;
  speaker_id_error: string | null;
  speaker_id_at: string | null;
  /** Live upload progress (status 'uploading' only): bytes landed on the
   * server so far / Content-Length total (null when the client didn't send
   * one). Written debounced during the stream, stale afterwards. */
  upload_bytes_received: number | null;
  upload_bytes_total: number | null;
}

/** One invitee of the source calendar event (Google Meet import). */
export interface GmeetAttendee {
  email: string;
  name?: string;
  responseStatus?: string;
}

/** One utterance parsed from a Google Meet transcript Doc. Times are ms,
 * interpolated within the Doc's block-level timestamps — approximate. */
export interface MeetUtterance {
  speaker: string;
  text: string;
  start: number;
  end: number;
}

/** One person who actually joined the conference (Meet REST API). Email is
 * resolved via the People API directory when possible — Meet itself only
 * returns an opaque `users/{id}` plus a display name. */
export interface MeetParticipantInfo {
  displayName: string;
  email?: string;
  personId?: string;
  kind: 'signedin' | 'anonymous' | 'phone';
  earliestStart?: string;
  latestEnd?: string;
}

/** One structured transcript entry from the Meet API (precise per-utterance
 * times, unlike the Doc's 5-minute blocks). `start`/`end` are ms relative to
 * `MeetActuals.anchorIso`. */
export interface MeetTranscriptEntry {
  speaker: string;
  email?: string;
  text: string;
  startIso?: string;
  endIso?: string;
  start: number;
  end: number;
}

/**
 * Ground truth captured from the Meet REST API at import time. Snapshotted
 * because parts of it EXPIRE — transcript entries are gone 30 days after the
 * meeting. `anchorIso` is the wall-clock zero used for all relative ms in
 * `transcriptEntries` (the first recording's start when one exists — which is
 * also AAI's t=0, making Meet↔AAI timeline alignment pure arithmetic).
 */
export interface MeetActuals {
  conferenceRecordName?: string;
  conferenceStart?: string;
  conferenceEnd?: string;
  recordings?: Array<{ fileId?: string; startTime?: string; endTime?: string }>;
  transcriptDocIds?: string[];
  participants?: MeetParticipantInfo[];
  transcriptEntries?: MeetTranscriptEntry[];
  entriesTruncated?: boolean;
  anchorIso?: string;
}

/**
 * Source-meeting metadata stored on rows imported from Google Meet / Drive
 * (`gmeet_context` column). `meetTranscript` is the parsed Meet transcript
 * kept as a sidecar — real speaker names from Google, useful for
 * cross-referencing against AAI's acoustic diarization. `actuals` is the
 * Meet API snapshot (participants, segment times, transcript entries).
 */
export interface GmeetContext {
  eventId?: string;
  /** Calendar's series key — the TRUE identity of a recurring meeting.
   * Meeting codes get recycled for unrelated meetings (people reuse one
   * Meet link), so when both exist this outranks meetingCode for "same
   * series" questions. */
  recurringEventId?: string;
  /** RFC-5545 UID — stable across calendar copies of the same event. */
  iCalUID?: string;
  organizerEmail?: string;
  eventTitle?: string;
  startTime?: string;
  endTime?: string;
  meetingCode?: string;
  attendees?: GmeetAttendee[];
  videoFileId?: string;
  transcriptDocId?: string;
  meetTranscript?: {
    attendees: string[];
    utterances: MeetUtterance[];
  } | null;
  actuals?: MeetActuals | null;
  /** Upload-time processing choices (upload-media stepper). `report` is what
   * the speaker-review confirm generates: quick summary (default when
   * absent), a detailed report, or nothing ('later' = pick on the page). */
  uploadPrefs?: {
    report?: 'summary' | 'detailed-video' | 'detailed-text' | 'later';
  } | null;
}

/** Access level for the current user on a transcript. */
export type TranscriptAccess = 'owner' | 'edit' | 'read';

/**
 * What the listing and detail endpoints return to the client: the row plus
 * the caller's computed access level and, for shared rows, the owner's name
 * to show in the UI.
 */
export interface TranscriptWithAccess extends StoredTranscript {
  access: TranscriptAccess;
  owner_email: string | null;
  owner_name: string | null;
}

/**
 * Skinny row returned by the listing endpoint. Deliberately excludes the
 * enormous `imported_content` JSONB, `audio_url`, and `local_audio_path`
 * fields — the listing page doesn't need them and they bloat responses to
 * tens of MB per row.
 */
export interface TranscriptListRow {
  id: number;
  user_id: string;
  assemblyai_id: string;
  original_filename: string | null;
  status: string;
  created_at: string;
  completed_at: string | null;
  duration: number | null;
  speaker_count: number | null;
  language_code: string | null;
  title: string | null;
  description: string | null;
  last_accessed: string;
  source: 'uploaded' | 'imported';
  recorded_at: string | null;
  auto_notes_status: string | null;
  upload_bytes_received: number | null;
  upload_bytes_total: number | null;
  access: TranscriptAccess;
  owner_email: string | null;
  owner_name: string | null;
}

/** A row from `transcript_shares`, as returned by /api/transcripts/:id/shares. */
export interface TranscriptShare {
  id: number;
  transcript_id: number;
  shared_with_email: string;
  shared_with_name: string | null;
  shared_with_ppl_id: number | null;
  access: 'edit' | 'read';
  shared_at: string;
}

/**
 * A user's speaker-label customisation for one transcript.
 * `description` is freeform notes — useful as LLM-postfix context (role, voice
 * description, "this is the engineer not the founder", etc.).
 */
export interface SpeakerLabel {
  originalSpeaker: string;
  customName: string;
  description: string;
}

/**
 * Auto-detection result for one diarized speaker, stored in
 * `speaker_mappings.suggestions` keyed by originalSpeaker.
 *
 * Two sources:
 *  - 'voice': ECAPA voiceprint match; `confidence` is cosine similarity
 *    (0..1; sub-threshold matches are never stored).
 *  - 'context': inferred by Claude from the transcript text during notes
 *    generation (self-introductions, being addressed by name); `evidence`
 *    is a short quote/justification, `confidence` is 0. Entries from the
 *    dedicated speaker-ID pass carry `via: 'id'` and a real confidence —
 *    the pass must not be fed its own prior output on re-runs.
 */
export interface SpeakerSuggestion {
  name: string;
  confidence: number;
  source?: 'voice' | 'context';
  /** 'id' = written by the dedicated speaker-identification pass */
  via?: 'id';
  evidence?: string;
}

export type SpeakerSuggestionMap = Record<string, SpeakerSuggestion>;

/**
 * "Attached context" on a transcript: a file (deck, PDF, doc) or
 * typed/pasted text that collaborators add. Visible to everyone with access
 * and injected into AI notes generation. `text_content` is the pasted text
 * or the server's best-effort extraction from the file.
 */
export interface TranscriptAttachment {
  id: number;
  transcript_id: number;
  added_by_user_id: string;
  added_by_email: string | null;
  kind: 'text' | 'file';
  title: string;
  text_content: string | null;
  original_filename: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  extraction_status: 'ok' | 'none' | 'failed' | null;
  created_at: string;
}

/** One AI-suggested topical section of the meeting. */
export interface TranscriptSegment {
  title: string;
  start_ms: number;
}

/** Per-utterance edit override stored in `transcript_edits.edits`. */
export interface UtteranceEdit {
  text?: string;
  speaker?: string;
}

/** Map of utterance index → override. */
export type TranscriptEditMap = Record<string, UtteranceEdit>;

/** A custom-spelling entry — replace any of `from[]` with `to`. */
export interface CustomSpellingEntry {
  to: string;
  from: string[];
}

/**
 * Vocab payload (per-user or org-wide).
 *
 * `keyterms_prompt` replaces the old `word_boost` (deprecated by AAI
 * 2026-Q2). It's a flat string array of phrases (up to 1000 entries, up
 * to 6 words per entry) that AAI uses to bias recognition when you submit
 * with the Universal-3 Pro / Slam-1 speech model. No per-entry weights,
 * no global boost param.
 */
export interface VocabPayload {
  keyterms_prompt: string[];
  custom_spelling: CustomSpellingEntry[];
}

export interface TranscriptResponse {
  id: string;
  status: 'queued' | 'processing' | 'completed' | 'error';
  text?: string;
  audio_url?: string;
  created: string;
  completed?: string;
  audio_duration?: number;
  utterances?: Array<{
    text: string;
    start: number;
    end: number;
    speaker: string;
  }>;
  error?: string;
  audio_start_from?: number;
  audio_end_at?: number;
  language_code?: string;
  confidence?: number;
  words?: Array<{
    text: string;
    start: number;
    end: number;
    confidence: number;
    speaker?: string;
  }>;
}

/** "512 MB", "1.2 GB" — for upload sizes/progress in the listing. */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024)));
  const v = bytes / 1024 ** i;
  return `${v >= 100 || i === 0 ? Math.round(v) : v.toFixed(1)} ${units[i]}`;
}

export function formatDuration(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = Math.floor(seconds % 60);

  if (minutes === 0) {
    return `${remainingSeconds}s`;
  } else if (minutes < 60) {
    return `${minutes}m ${remainingSeconds}s`;
  } else {
    const hours = Math.floor(minutes / 60);
    const remainingMinutes = minutes % 60;
    return `${hours}h ${remainingMinutes}m`;
  }
}

/**
 * Scannable date: "Today 14:05" / "Yesterday" / "Tuesday" (<7 days) /
 * "12 Jun" (same year) / "12 Jun 2025". Pair with a `title` attribute
 * carrying the full locale timestamp for precision on demand.
 */
export function formatSmartDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const now = new Date();
  const startOfDay = (x: Date) => new Date(x.getFullYear(), x.getMonth(), x.getDate());
  const dayDiff = Math.round(
    (startOfDay(now).getTime() - startOfDay(d).getTime()) / 86_400_000
  );
  if (dayDiff === 0) {
    return `Today ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  }
  if (dayDiff === 1) return 'Yesterday';
  if (dayDiff > 1 && dayDiff < 7) return d.toLocaleDateString([], { weekday: 'long' });
  if (d.getFullYear() === now.getFullYear()) {
    return d.toLocaleDateString([], { day: 'numeric', month: 'short' });
  }
  return d.toLocaleDateString([], { day: 'numeric', month: 'short', year: 'numeric' });
}

export function formatTime(milliseconds: number): string {
  const totalSeconds = Math.floor(milliseconds / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const remainingSeconds = totalSeconds % 60;
  return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
}
