/**
 * Shared (client + server) types and formatters for transcripts.
 *
 * Do NOT put anything here that touches the AssemblyAI SDK or server-only
 * state — this file is imported from client components.
 */

/** Temporary (scratch) transcripts are moved to the trash this many days
 * after creation (migration 042). The sweeper, the listing hint and the
 * detail-page banner all read this one number. */
export const SCRATCH_TTL_DAYS = 30;

/** When a temporary transcript created at `createdAt` gets auto-trashed. */
export function scratchTrashDate(createdAt: string): Date {
  return new Date(new Date(createdAt).getTime() + SCRATCH_TTL_DAYS * 86_400_000);
}

/** A row from our `transcripts` table, as returned by /api/transcripts. */
export interface StoredTranscript {
  id: number;
  user_id: string;
  assemblyai_id: string;
  original_filename: string | null;
  status: string;
  created_at: string;
  completed_at: string | null;
  duration: number | null;
  speaker_count: number | null;
  language_code: string | null;
  title: string | null;
  description: string | null;
  last_accessed: string;
  source: 'uploaded' | 'imported';
  /** AssemblyAI speech model the row was transcribed with; null = pre-column
   * row (ran on 'universal') or a quick import that never ran AAI. */
  speech_model: string | null;
  /** present only when source = 'imported'; the full AAI payload frozen at import time */
  imported_content: TranscriptResponse | null;
  /** cached AAI audio_url at the time of upload/import (may stop working over time) */
  audio_url: string | null;
  /** server-local fallback audio file (set during import after we download the bytes) */
  local_audio_path: string | null;
  /** Drive file ID of the source recording (Google Meet import) — dedupe key */
  drive_file_id: string | null;
  /** source-meeting metadata for Google Meet imports */
  gmeet_context: GmeetContext | null;
  /** when the meeting actually happened (vs created_at = upload time); from
   * the linked calendar event/conference, or set by hand */
  recorded_at: string | null;
  /** AI meeting notes generated by headless Claude on the server (markdown) */
  auto_notes: string | null;
  /** AI-suggested topical segments, ordered by start_ms */
  auto_segments: TranscriptSegment[] | null;
  /** null = never attempted; 'running' | 'completed' | 'error' */
  auto_notes_status: string | null;
  auto_notes_error: string | null;
  auto_notes_at: string | null;
  /** Detailed wiki-style AI report (markdown with frame images, t: links) */
  auto_report: string | null;
  auto_report_status: string | null;
  auto_report_error: string | null;
  auto_report_at: string | null;
  /** Speaker-identification AI pass (runs at completion, before notes).
   * null = never attempted; 'running' | 'completed' | 'error' */
  speaker_id_status: string | null;
  speaker_id_error: string | null;
  speaker_id_at: string | null;
  /** Live upload progress (status 'uploading' only): bytes landed on the
   * server so far / Content-Length total (null when the client didn't send
   * one). Written debounced during the stream, stale afterwards. */
  upload_bytes_received: number | null;
  upload_bytes_total: number | null;
  /** Soft delete (trash): set = hidden from listings/search/series/dedupe
   * and every background job; restore clears it. Row, AAI transcript,
   * audio, shares, and notes all survive until a permanent delete. */
  deleted_at: string | null;
  /** Temporary (scratch) transcript (migration 042): kept out of the main
   * listing / search / series / dedupe / already-imported lookups, listed
   * under the Temporary tab instead, auto-trashed 30 days after creation.
   * Still a real transcript everywhere else (detail page, AI passes,
   * sharing, labels). Linking a calendar event clears it. */
  scratch: boolean;
}

/** One invitee of the source calendar event (Google Meet import). */
export interface GmeetAttendee {
  email: string;
  name?: string;
  responseStatus?: string;
}

/** One utterance parsed from a Google Meet transcript Doc. Times are ms,
 * interpolated within the Doc's block-level timestamps — approximate. */
export interface MeetUtterance {
  speaker: string;
  text: string;
  start: number;
  end: number;
}

/** One person who actually joined the conference (Meet REST API). Email is
 * resolved via the People API directory when possible — Meet itself only
 * returns an opaque `users/{id}` plus a display name. */
export interface MeetParticipantInfo {
  displayName: string;
  email?: string;
  personId?: string;
  kind: 'signedin' | 'anonymous' | 'phone';
  earliestStart?: string;
  latestEnd?: string;
}

/** One structured transcript entry from the Meet API (precise per-utterance
 * times, unlike the Doc's 5-minute blocks). `start`/`end` are ms relative to
 * `MeetActuals.anchorIso`. */
export interface MeetTranscriptEntry {
  speaker: string;
  email?: string;
  text: string;
  startIso?: string;
  endIso?: string;
  start: number;
  end: number;
}

/**
 * Ground truth captured from the Meet REST API at import time. Snapshotted
 * because parts of it EXPIRE — transcript entries are gone 30 days after the
 * meeting. `anchorIso` is the wall-clock zero used for all relative ms in
 * `transcriptEntries` (the first recording's start when one exists — which is
 * also AAI's t=0, making Meet↔AAI timeline alignment pure arithmetic).
 */
export interface MeetActuals {
  conferenceRecordName?: string;
  conferenceStart?: string;
  conferenceEnd?: string;
  recordings?: Array<{ fileId?: string; startTime?: string; endTime?: string }>;
  transcriptDocIds?: string[];
  participants?: MeetParticipantInfo[];
  transcriptEntries?: MeetTranscriptEntry[];
  entriesTruncated?: boolean;
  anchorIso?: string;
  /** How many transcript SESSIONS Meet listed, whether or not their Doc has
   * been generated yet. transcriptsListed > 0 with no transcriptDocIds =
   * "Google is still preparing the transcript Doc". */
  transcriptsListed?: number;
}

/**
 * Source-meeting metadata stored on rows imported from Google Meet / Drive
 * (`gmeet_context` column). `meetTranscript` is the parsed Meet transcript
 * kept as a sidecar — real speaker names from Google, useful for
 * cross-referencing against AAI's acoustic diarization. `actuals` is the
 * Meet API snapshot (participants, segment times, transcript entries).
 */
export interface GmeetContext {
  /** Which conferencing product the source meeting ran on. Absent or
   * 'gmeet' = Google Meet (backward compat with every pre-Teams row). */
  provider?: 'gmeet' | 'teams';
  /** "Re-transcribe with the newer model": on the NEW row, the id of the
   * row it was re-run from; on the OLD row, when/where the re-run went so
   * the button turns into a pointer instead of firing twice. */
  retranscribedFrom?: string;
  retranscribed?: { at: string; newId: string; model: string };
  /** Microsoft Teams source facts (provider === 'teams'). Artifacts are
   * fetched app-only under the ORGANIZER's AAD id — no per-user Microsoft
   * auth exists. `callId` keys the specific occurrence of a recurring
   * series; transcript+recording of one occurrence share it. */
  teams?: {
    /** Canonical meetup-join URL (what Graph's $filter matches). */
    joinWebUrl: string;
    tenantId: string;
    organizerOid: string;
    graphMeetingId: string;
    callId?: string;
    transcriptId?: string;
    /** Presence enables fetch-recording-later, like videoFileId for Meet. */
    recordingId?: string;
  } | null;
  eventId?: string;
  /** Calendar's series key — the TRUE identity of a recurring meeting.
   * Meeting codes get recycled for unrelated meetings (people reuse one
   * Meet link), so when both exist this outranks meetingCode for "same
   * series" questions. */
  recurringEventId?: string;
  /** RFC-5545 UID — stable across calendar copies of the same event. */
  iCalUID?: string;
  organizerEmail?: string;
  eventTitle?: string;
  startTime?: string;
  endTime?: string;
  meetingCode?: string;
  attendees?: GmeetAttendee[];
  videoFileId?: string;
  /** Recording segments BEYOND the primary video (someone stopped and
   * restarted recording mid-meeting — Meet makes one Drive file per run).
   * The primary (`videoFileId` → `local_audio_path`) is what AAI transcribed;
   * these are the meeting's other videos, fetched to
   * `<assemblyaiId>.part<N>.<ext>` sidecar files so nothing silently
   * disappears. `filename` present = bytes stored and playable via
   * /audio?part=N. Ordered chronologically; part number = index + 2
   * (the primary is "Video 1"). */
  videoParts?: Array<{
    fileId: string;
    startTime?: string;
    endTime?: string;
    filename?: string;
    bytes?: number;
    fetchedAt?: string;
  }>;
  transcriptDocId?: string;
  /** This row's media is a CONCATENATION of a multi-video meeting's segments
   * (re-transcribe-all-videos flow): the number of videos combined. Times in
   * the transcript are concat-time — inter-segment gaps removed; the carried
   * meetTranscript sidecar was remapped to match at combine time. */
  combinedParts?: number;
  /** Set at import time when Meet listed ANY recording whose file Google was
   * still generating (state ENDED, no Drive id yet) — including a second/third
   * segment of a stop-restart recording while the first is already imported.
   * The recording poller re-checks every minute and attaches each video when
   * it lands (primary if none yet, else a videoParts entry); `status` leaves
   * 'waiting' exactly once. */
  recordingPending?: {
    recordName: string;
    since: string;
    lastCheckedAt?: string;
    attempts?: number;
    status: 'waiting' | 'fetched' | 'gone' | 'gave-up';
    resolvedAt?: string;
  } | null;
  /** Resume-sweep bookkeeping (recording poller): for a few hours after an
   * import that captured a conference record, the meeting code's records are
   * re-listed — hanging up and rejoining the same Meet link makes Google open
   * a SECOND conferenceRecord whose artifacts nothing else would ever see
   * (discovery's nearestRecord always picks the imported one, and auto-sync's
   * occKey claim blocks a re-import). Each ended sibling record found is
   * "adopted" by re-arming `recordingPending` against it, so its videos land
   * as videoParts through the existing diff-attach machinery. */
  resumeWatch?: {
    /** Records already accounted for: the imported one + adopted siblings. */
    knownRecords: string[];
    since: string;
    lastCheckedAt?: string;
    attempts?: number;
    status: 'watching' | 'done';
    resolvedAt?: string;
    /** Resumed sessions detected, latest known state. `adoptedAt` set once
     * recordingPending was re-armed on it (or `empty` — ended unrecorded). */
    found?: Array<{
      recordName: string;
      startTime?: string;
      endTime?: string;
      adoptedAt?: string;
      empty?: boolean;
    }>;
  } | null;
  /** Set when the resume sweep adopts a sibling record: once every part's
   * bytes are stored, no recordingPending wait is open and no further
   * sitting is live, the sweep re-runs the import from local (the
   * combine-all-videos re-transcribe flow, executeGmeetImport with
   * sourceTranscriptId) so the transcript covers every sitting — the /m
   * uuid repoints to the combined row. Auto/import markers are carried, so
   * an auto-synced meeting stays a fully unattended pipeline. */
  pendingRecombine?: {
    since: string;
    status: 'waiting' | 'fired' | 'failed';
    attempts?: number;
    firedAt?: string;
    /** assemblyai_id of the combined row the re-run created. */
    newId?: string;
    error?: string;
  } | null;
  /** Background video-fetch bookkeeping: a known-but-undownloaded recording
   * (videoFileId / teams.recordingId, no local audio) is pulled by the
   * video-fetch sweeper without waiting for a page visit. Attempts are
   * capped with backoff; 'gave-up' rows still retry on page-visit/manual
   * fetch, which clears this on success via local_audio_path. */
  videoAutoFetch?: {
    attempts: number;
    lastAttemptAt: string;
    status: 'pending' | 'gave-up';
    lastError?: string;
  } | null;
  /** Playback-media preparation state (lib/server/media-sweeper.ts):
   * `faststart` = every stored file (primary + fetched videoParts) has its
   * mp4 index up front; `audioOnly` = the 64 kbps mono extract exists (or
   * is not needed — the source has no video); `parts` = how many stored
   * videoParts were covered, so a part that lands later re-qualifies the
   * row. Stamped at import and by the 5-min backfill sweeper; `attempts`
   * + `error` throttle retries of a row whose ffmpeg keeps failing. */
  media?: {
    faststart: boolean;
    audioOnly: boolean;
    parts: number;
    at: string;
    attempts?: number;
    error?: string;
  } | null;
  /** A "detailed report — with video frames" requested while the recording
   * was still being prepared (recordingPending 'waiting', no fileId to pull
   * yet). The recording poller fires the report the moment the video lands
   * and clears this; if the recording never materializes (gone / gave-up)
   * the report still runs, degraded to text-only. */
  pendingVideoReport?: {
    instructions?: string;
    triggeredBy?: { userId: string; email: string };
    requestedAt: string;
    /** T4: fire at/after this instant instead of when the recording lands.
     * The recording-poller's due-report pass fires it; a recording landing
     * EARLIER leaves the marker alone (schedule wins). */
    runAfter?: string;
    /** T4: scheduled runs remember the frames choice (default true). */
    useVideo?: boolean;
  } | null;
  /** Multi-file single-meeting upload, in flight: bookkeeping while the
   * group's files stream in one by one (part k>1 lands as
   * `upload-<uuid>.part<k>`). Cleared when the last part triggers the
   * stitch + ingest; the durable record is `uploadedParts`. */
  uploadGroup?: {
    id: string;
    total: number;
    parts: Array<{
      index: number;
      tempFilename: string;
      originalFilename?: string;
      comment?: string;
      bytes?: number;
    }>;
  } | null;
  /** The stitched-media map of a multi-file upload: one entry per source
   * file in stitch order, with the user's per-file comment. `offsetSec` is
   * where the file starts on the combined timeline. Fed into the AI prompts
   * so the model understands the stitch points and any per-file caveats
   * ("room mic", "Zoom rejoin after the drop"). */
  uploadedParts?: Array<{
    index: number;
    originalFilename?: string;
    comment?: string;
    durationSec?: number;
    offsetSec?: number;
  }> | null;
  /** Import queued while Google was still preparing the needed artifact
   * (transcript Doc for 'transcript' mode, video file for 'video', both for
   * 'both'). Lives on a `defer-…` placeholder row (status 'waiting'); the
   * deferred-import poller re-checks every minute and replays the frozen
   * `request` with the owner's server token the moment the dependency lands.
   * On success the placeholder is promoted (video modes) or deleted in favor
   * of the real imported row (transcript mode). */
  /** Transcription hand-off failed AFTER the bytes were safely stored on our
   * disk (AssemblyAI upload/submit error — account balance negative, AAI 5xx,
   * network). The placeholder row stays visible as Failed, the file is kept
   * under the placeholder id, and the ingest-retry sweeper re-submits it with
   * backoff until it lands or `retryable` is cleared (72 h). Cleared on
   * success. POST /api/transcripts/:id/retry-ingest does it on demand. */
  ingestFailure?: {
    stage: 'aai-upload' | 'aai-submit';
    message: string;
    firstAt: string;
    at: string;
    attempts: number;
    nextAt: string | null;
    retryable: boolean;
    /** The ingest options frozen for the replay. */
    opts: {
      originalFilename: string | null;
      languageCode?: string;
      title?: string | null;
      extraKeyterms?: string[];
      speechModel?: string;
    };
  };
  deferredImport?: {
    mode: 'video' | 'transcript' | 'both';
    /** Owner's email at queue time (needed for dedupe + share resolution —
     * there is no users table to look it up from later). */
    ownerEmail: string;
    /** Queued with the artifacts already ready — the poller runs it right
     * away; the listing words it "importing" rather than "waiting". */
    background?: boolean;
    /** The import request frozen at queue time, replayed verbatim (plus the
     * artifact ids discovered by the poller) when the provider finishes. */
    request: {
      /** Teams deferrals only: the canonical meetup-join URL the poller
       * re-resolves through Graph (Meet deferrals use conferenceRecordName). */
      url?: string;
      videoFileId?: string;
      transcriptDocId?: string;
      languageCode?: string;
      conferenceRecordName?: string;
      force?: boolean;
      event?: {
        id?: string;
        title?: string;
        startTime?: string;
        endTime?: string;
        meetingCode?: string;
        recurringEventId?: string;
        iCalUID?: string;
        organizerEmail?: string;
        attendees?: GmeetAttendee[];
      };
      /** Extra gmeet_context fields to stamp on the row the replay creates
       * (series auto-import marker + report pref) — frozen with the request
       * so they survive the placeholder→real-row promotion in every mode. */
      contextExtra?: {
        autoImport?: GmeetContext['autoImport'];
        autoSync?: GmeetContext['autoSync'];
        uploadPrefs?: GmeetContext['uploadPrefs'];
      };
    };
    since: string;
    lastCheckedAt?: string;
    /** Cheap artifact-listing checks. */
    attempts?: number;
    /** Full import executions that failed (backed off separately). */
    execAttempts?: number;
    lastExecAt?: string;
    status: 'waiting' | 'done' | 'failed' | 'gave-up';
    error?: string;
    resolvedAt?: string;
  } | null;
  meetTranscript?: {
    attendees: string[];
    utterances: MeetUtterance[];
  } | null;
  actuals?: MeetActuals | null;
  /** Upload-time processing choices (upload-media stepper). `report` is what
   * the speaker-review confirm generates: quick summary (default when
   * absent), a detailed report, or nothing ('later' = pick on the page). */
  uploadPrefs?: {
    report?: 'summary' | 'detailed-video' | 'detailed-text' | 'later';
  } | null;
  /** Stamped by the series auto-import sweep on rows it fires: which series
   * occurrence this import came from and whose connection ran it. Presence
   * of this marker is what arms the automatic speaker-review evaluation. */
  autoImport?: {
    seriesId: number;
    seriesTitle?: string;
    occKey: string;
    byUserId: string;
    byEmail: string;
    /** Account-auto-sync users who were in the meeting (since 2026-09-08):
     * shared onto the row and DM'd at every stage, same as autoSync.watchers.
     * Absent on older rows. Read via lib/auto-marker autoMarkerOf(). */
    watchers?: string[];
    at: string;
  } | null;
  /** Stamped by the ACCOUNT auto-sync sweep (T2, lib/server/account-auto-
   * sync) on rows it fires: which occurrence, whose Google connection ran
   * the import (the elected importer) and which other auto-sync users
   * wanted it (watchers — shared in and DM'd alongside the importer). Arms
   * the automatic speaker-review evaluation exactly like autoImport. */
  autoSync?: {
    occKey: string;
    byUserId: string;
    byEmail: string;
    watchers: string[];
    at: string;
  } | null;
  /** Outcome of the automatic speaker-review evaluation that runs after the
   * speaker-ID pass on auto-imported rows. passed=true → suggested names
   * were applied and generation fired unattended (rendered as the "auto"
   * dot in the listing); passed=false → the normal human review gate holds
   * and the owner got a needs-review DM. */
  autoReview?: {
    evaluatedAt: string;
    passed: boolean;
    reason?: string;
    /** What was generated unattended (mirrors uploadPrefs.report). */
    generated?: 'summary' | 'detailed-video' | 'detailed-text' | null;
  } | null;
  /** Stamped by the notes sweeper when a temporary (scratch) row's 30 days
   * ran out and the owner was DM'd about the auto-trash — one DM per row,
   * ever (the plagueis dedupe key is the belt, this marker the braces). */
  scratchTrashDm?: { at: string; to: string } | null;
}

/** Access level for the current user on a transcript. */
export type TranscriptAccess = 'owner' | 'edit' | 'read';

/**
 * What the listing and detail endpoints return to the client: the row plus
 * the caller's computed access level and, for shared rows, the owner's name
 * to show in the UI.
 */
export interface TranscriptWithAccess extends StoredTranscript {
  access: TranscriptAccess;
  owner_email: string | null;
  owner_name: string | null;
}

/** Minimal label reference carried on listing rows / chips (mirror of
 * `LabelRef` in src/lib/labels.ts — kept here so format.ts stays the one
 * place wire shapes are declared). */
export interface LabelRef {
  id: number;
  name: string;
  path: string;
  color: string | null;
}

/**
 * Skinny row returned by the listing endpoint. Deliberately excludes the
 * enormous `imported_content` JSONB, `audio_url`, and `local_audio_path`
 * fields — the listing page doesn't need them and they bloat responses to
 * tens of MB per row.
 */
export interface TranscriptListRow {
  id: number;
  user_id: string;
  assemblyai_id: string;
  original_filename: string | null;
  status: string;
  created_at: string;
  completed_at: string | null;
  duration: number | null;
  speaker_count: number | null;
  language_code: string | null;
  title: string | null;
  description: string | null;
  last_accessed: string;
  source: 'uploaded' | 'imported';
  speech_model?: string | null;
  recorded_at: string | null;
  auto_notes_status: string | null;
  upload_bytes_received: number | null;
  upload_bytes_total: number | null;
  /** Conferencing product of the source meeting (listing glyphs); null =
   * plain upload/import with no meeting identity. */
  provider?: 'gmeet' | 'teams' | null;
  /** Calendar event linked (gmeet_context.eventId present). */
  has_event?: boolean;
  /** Recurring-call series membership (the series badge). */
  series_id?: number | null;
  series_title?: string | null;
  /** Best evidence-key guess for untagged rows (the dashed "…?" chip). */
  suspected_series_id?: number | null;
  suspected_series_title?: string | null;
  /** Set on `defer-…` placeholder rows (status 'waiting', or 'error' after
   * give-up): the queued import's mode, for the listing's waiting/failed
   * copy. */
  deferred_mode?: 'video' | 'transcript' | 'both' | null;
  deferred_error?: string | null;
  /** 'true' when the queued import's artifacts were ready at queue time (a
   * background run, actively importing) — jsonb ->> yields text. */
  deferred_background?: string | null;
  /** Meetings with more than one recording: extra Meet segments beyond the
   * primary, a stitched multi-file upload, or a combined re-transcription.
   * 1 (or absent — legacy/v1 payloads) = single recording. */
  recording_count?: number;
  /** Series auto-import lifecycle: 'passed' = fully unattended (imported +
   * speakers auto-identified + report generated — the blue dot), 'gated' =
   * auto-imported but waiting on human speaker review, 'auto' = imported by
   * the sweep, review not yet evaluated. Absent = manual import/upload. */
  auto_state?: 'passed' | 'gated' | 'auto' | null;
  /** Set on trash-view rows only (the main listing never returns them). */
  deleted_at?: string | null;
  /** Temporary (scratch) transcript — see StoredTranscript.scratch. The main
   * listing never returns scratch rows; the Temporary tab (`?scratch=1` /
   * `?v=2&tab=scratch`) and the trash view carry the flag so clients can
   * hint "temporary · trashed on <date>". */
  scratch?: boolean;
  /** v2 listing with `q`: which field the search matched (first-match
   * priority title→filename→description→notes→content). */
  matched_in?: 'title' | 'filename' | 'description' | 'notes' | 'content';
  /** v2 listing with `q`: SQL-cut context around the match (null for
   * title/filename hits — the match is already visible on the row). */
  snippet?: string | null;
  access: TranscriptAccess;
  owner_email: string | null;
  owner_name: string | null;
  /** v2 listing only: org-wide labels on this transcript, sorted by path_key
   * (docs/labels-design.md §7). Absent on the legacy (no-params) listing,
   * which stays byte-identical. */
  labels?: LabelRef[];
}

/** One day bucket of the paginated v2 listing. `key` is the day in the
 * caller's requested timezone (YYYY-MM-DD); days are never split across
 * pages. `totalSecs` sums `duration` over this day's rows (nulls as 0). */
export interface TranscriptDayGroup {
  key: string;
  rows: TranscriptListRow[];
  totalSecs: number;
}

/** Tab badge counts for the v2 listing. all/mine/shared respect the active
 * from/to + q filters; trash is the caller's global trashed-row count;
 * scratch is the caller's visible (owned + shared) live temporary-row count. */
export interface TranscriptListCounts {
  all: number;
  mine: number;
  shared: number;
  trash: number;
  /** Absent on payloads cached before migration 042 — treat as 0. */
  scratch?: number;
}

/** Envelope of GET /api/transcripts?v=2 — day-bucketed pagination. The
 * cursor is a day key (exclusive): the next page holds strictly older days. */
export interface TranscriptListV2Response {
  days: TranscriptDayGroup[];
  counts: TranscriptListCounts;
  nextCursor: string | null;
  hasMore: boolean;
}

/** A row from `transcript_shares`, as returned by /api/transcripts/:id/shares. */
export interface TranscriptShare {
  id: number;
  transcript_id: number;
  shared_with_email: string;
  shared_with_name: string | null;
  shared_with_ppl_id: number | null;
  access: 'edit' | 'read';
  shared_at: string;
}

/**
 * A user's speaker-label customisation for one transcript.
 * `description` is freeform notes — useful as LLM-postfix context (role, voice
 * description, "this is the engineer not the founder", etc.).
 */
export interface SpeakerLabel {
  originalSpeaker: string;
  customName: string;
  description: string;
}

/**
 * Auto-detection result for one diarized speaker, stored in
 * `speaker_mappings.suggestions` keyed by originalSpeaker.
 *
 * Two sources:
 *  - 'voice': ECAPA voiceprint match; `confidence` is cosine similarity
 *    (0..1; sub-threshold matches are never stored).
 *  - 'context': inferred by Claude from the transcript text during notes
 *    generation (self-introductions, being addressed by name); `evidence`
 *    is a short quote/justification, `confidence` is 0. Entries from the
 *    dedicated speaker-ID pass carry `via: 'id'` and a real confidence —
 *    the pass must not be fed its own prior output on re-runs.
 */
export interface SpeakerSuggestion {
  name: string;
  confidence: number;
  source?: 'voice' | 'context';
  /** 'id' = written by the dedicated speaker-identification pass */
  via?: 'id';
  evidence?: string;
}

export type SpeakerSuggestionMap = Record<string, SpeakerSuggestion>;

/**
 * "Attached context" on a transcript: a file (deck, PDF, doc) or
 * typed/pasted text that collaborators add. Visible to everyone with access
 * and injected into AI notes generation. `text_content` is the pasted text
 * or the server's best-effort extraction from the file.
 */
export interface TranscriptAttachment {
  id: number;
  transcript_id: number;
  added_by_user_id: string;
  added_by_email: string | null;
  kind: 'text' | 'file';
  title: string;
  text_content: string | null;
  original_filename: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  extraction_status: 'ok' | 'none' | 'failed' | null;
  created_at: string;
}

/** One AI-suggested topical section of the meeting. */
export interface TranscriptSegment {
  title: string;
  start_ms: number;
}

/** Per-utterance edit override stored in `transcript_edits.edits`. */
export interface UtteranceEdit {
  text?: string;
  speaker?: string;
}

/** Map of utterance index → override. */
export type TranscriptEditMap = Record<string, UtteranceEdit>;

/** A custom-spelling entry — replace any of `from[]` with `to`. */
export interface CustomSpellingEntry {
  to: string;
  from: string[];
}

/**
 * Vocab payload (per-user or org-wide).
 *
 * `keyterms_prompt` replaces the old `word_boost` (deprecated by AAI
 * 2026-Q2). It's a flat string array of phrases (up to 1000 entries, up
 * to 6 words per entry) that AAI uses to bias recognition when you submit
 * with the Universal-3 Pro / Slam-1 speech model. No per-entry weights,
 * no global boost param.
 */
export interface VocabPayload {
  keyterms_prompt: string[];
  custom_spelling: CustomSpellingEntry[];
}

export interface TranscriptResponse {
  id: string;
  status: 'queued' | 'processing' | 'completed' | 'error';
  text?: string;
  audio_url?: string;
  created: string;
  completed?: string;
  audio_duration?: number;
  utterances?: Array<{
    text: string;
    start: number;
    end: number;
    speaker: string;
  }>;
  error?: string;
  audio_start_from?: number;
  audio_end_at?: number;
  language_code?: string;
  confidence?: number;
  words?: Array<{
    text: string;
    start: number;
    end: number;
    confidence: number;
    speaker?: string;
  }>;
}

/** "512 MB", "1.2 GB" — for upload sizes/progress in the listing. */
export function formatBytes(bytes: number): string {
  if (!Number.isFinite(bytes) || bytes <= 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.min(units.length - 1, Math.floor(Math.log(bytes) / Math.log(1024)));
  const v = bytes / 1024 ** i;
  return `${v >= 100 || i === 0 ? Math.round(v) : v.toFixed(1)} ${units[i]}`;
}

export function formatDuration(seconds: number): string {
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = Math.floor(seconds % 60);

  if (minutes === 0) {
    return `${remainingSeconds}s`;
  } else if (minutes < 60) {
    return `${minutes}m ${remainingSeconds}s`;
  } else {
    const hours = Math.floor(minutes / 60);
    const remainingMinutes = minutes % 60;
    return `${hours}h ${remainingMinutes}m`;
  }
}

/**
 * Scannable date: "Today 14:05" / "Yesterday" / "Tuesday" (<7 days) /
 * "12 Jun" (same year) / "12 Jun 2025". Pair with a `title` attribute
 * carrying the full locale timestamp for precision on demand.
 */
export function formatSmartDate(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return '';
  const now = new Date();
  const startOfDay = (x: Date) => new Date(x.getFullYear(), x.getMonth(), x.getDate());
  const dayDiff = Math.round(
    (startOfDay(now).getTime() - startOfDay(d).getTime()) / 86_400_000
  );
  if (dayDiff === 0) {
    return `Today ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  }
  if (dayDiff === 1) return 'Yesterday';
  if (dayDiff > 1 && dayDiff < 7) return d.toLocaleDateString([], { weekday: 'long' });
  if (d.getFullYear() === now.getFullYear()) {
    return d.toLocaleDateString([], { day: 'numeric', month: 'short' });
  }
  return d.toLocaleDateString([], { day: 'numeric', month: 'short', year: 'numeric' });
}

/** Compact relative age: "just now" / "12m ago" / "3h ago" / "2d ago". */
export function formatAgo(iso: string): string {
  const t = new Date(iso).getTime();
  if (Number.isNaN(t)) return '';
  const mins = Math.max(0, Math.floor((Date.now() - t) / 60_000));
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hours = Math.floor(mins / 60);
  if (hours < 24) return `${hours}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

export function formatTime(milliseconds: number): string {
  const totalSeconds = Math.floor(milliseconds / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const remainingSeconds = totalSeconds % 60;
  return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`;
}

// ---------------------------------------------------------------------------
// Teams chat evidence (system messages in the meeting's Teams chat, read via
// the caller's Darth Tasks Microsoft link). Tells us whether an occurrence was
// HELD (and for how long) and whether anyone RECORDED it — even for meetings
// hosted by external tenants, where the app-only artifact probe is blind.
// Stored on the gmeet_meeting_cache row as raw.teamsChat; surfaced by
// /api/teams/evidence (`chat`), /api/teams/check (`chat`) and the norec view
// rows (the flat chat* fields below).
// ---------------------------------------------------------------------------

export interface TeamsChatVerdict {
  checkedAt: string;
  byEmail?: string | null;
  held: boolean;
  callStart: string | null;
  callEnd: string | null;
  durationMs: number | null;
  recorded: boolean;
  transcribed?: boolean;
  humanMessages?: number | null;
  /** Set when the chat could not be read for the window — the verdict is
   * then "no signal", not "not held": forbidden (external tenant, chat not
   * visible to the caller) | not_found | throttled | graph_error |
   * not_linked | revoked. */
  reason?: string | null;
}

/** Reasons that carry a user-facing verdict of their own (the chat exists
 * but we cannot read it). Transient/link reasons yield no verdict at all —
 * the row falls back to the connect hint / plain "nothing to import" copy. */
const TEAMS_CHAT_SHOWN_REASONS = new Set(['forbidden', 'not_found']);

function usableTeamsChatReason(reason: unknown): string | null {
  return typeof reason === 'string' && TEAMS_CHAT_SHOWN_REASONS.has(reason) ? reason : null;
}

/** Additive norec-row fields (CalendarMeetingRow) carrying the same verdict. */
export interface TeamsChatRowFields {
  chatHeld?: boolean | null;
  chatCallStart?: string | null;
  chatCallEnd?: string | null;
  chatDurationMs?: number | null;
  chatRecorded?: boolean | null;
  chatCheckedAt?: string | null;
  /** Optional extras the server may expose; read defensively. */
  chatReason?: string | null;
  chatExternal?: boolean | null;
}

/** Flat row fields → verdict, or null when the chat was never checked (or
 * the check produced no signal — reason set, held unknown). */
export function teamsChatVerdictFromRow(r: TeamsChatRowFields): TeamsChatVerdict | null {
  if (!r.chatCheckedAt) return null;
  const reason = usableTeamsChatReason(r.chatReason);
  // A reason means the chat was NOT read: held/recorded are meaningless then.
  if (r.chatReason && !reason) return null;
  if (!reason && typeof r.chatHeld !== 'boolean') return null;
  return {
    checkedAt: r.chatCheckedAt,
    held: reason ? false : r.chatHeld === true,
    callStart: reason ? null : (r.chatCallStart ?? null),
    callEnd: reason ? null : (r.chatCallEnd ?? null),
    durationMs: reason ? null : (r.chatDurationMs ?? null),
    recorded: reason ? false : r.chatRecorded === true,
    reason,
  };
}

/** Accept the shape an API hands back and keep only a usable verdict. */
export function asTeamsChatVerdict(v: unknown): TeamsChatVerdict | null {
  if (!v || typeof v !== 'object') return null;
  const o = v as Partial<TeamsChatVerdict>;
  if (typeof o.checkedAt !== 'string') return null;
  const reason = usableTeamsChatReason(o.reason);
  if (o.reason && !reason) return null; // not_linked / throttled / … → no verdict
  if (!reason && typeof o.held !== 'boolean') return null;
  if (reason) {
    return {
      checkedAt: o.checkedAt,
      byEmail: o.byEmail ?? null,
      held: false,
      callStart: null,
      callEnd: null,
      durationMs: null,
      recorded: false,
      transcribed: false,
      humanMessages: null,
      reason,
    };
  }
  return {
    checkedAt: o.checkedAt,
    byEmail: o.byEmail ?? null,
    held: o.held === true,
    callStart: o.callStart ?? null,
    callEnd: o.callEnd ?? null,
    durationMs: typeof o.durationMs === 'number' ? o.durationMs : null,
    recorded: o.recorded === true,
    transcribed: o.transcribed === true,
    humanMessages: typeof o.humanMessages === 'number' ? o.humanMessages : null,
    reason: null,
  };
}

/** "51 min" / "1 h 05 min" for a held-call duration. */
export function formatHeldMinutes(durationMs: number): string {
  const mins = Math.max(1, Math.round(durationMs / 60_000));
  if (mins < 60) return `${mins} min`;
  const h = Math.floor(mins / 60);
  const m = mins % 60;
  return m ? `${h} h ${String(m).padStart(2, '0')} min` : `${h} h`;
}

/**
 * One-line verdict copy for a Teams occurrence with no importable evidence,
 * from the chat check. `external`: organized outside our tenant (true), our
 * own tenant (false), unknown (null). `tone` drives the colour: 'warn' when
 * a recording exists that we cannot import (yet).
 */
export function teamsChatVerdictCopy(
  v: TeamsChatVerdict,
  opts: { external: boolean | null }
): { text: string; tone: 'neutral' | 'info' | 'warn'; title: string } {
  const fmt = (iso: string | null) => (iso ? new Date(iso).toLocaleString() : null);
  const titleParts = [`Source: Teams chat · checked ${fmt(v.checkedAt) ?? v.checkedAt}`];
  if (v.held && v.callStart) {
    titleParts.push(
      `Call ${new Date(v.callStart).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}` +
        (v.callEnd
          ? `–${new Date(v.callEnd).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`
          : '')
    );
  }
  if (v.reason === 'forbidden') {
    return {
      text: 'Teams chat not visible to you (external tenant)',
      tone: 'neutral',
      title: `${titleParts.join(' · ')} · the organizer's tenant did not let your account read the meeting chat`,
    };
  }
  if (v.reason === 'not_found') {
    return {
      text: 'Teams chat not found',
      tone: 'neutral',
      title: `${titleParts.join(' · ')} · Microsoft has no chat for this meeting link under your account`,
    };
  }
  if (!v.held) {
    return {
      text: 'Not held — nobody joined the call',
      tone: 'neutral',
      title: titleParts.join(' · '),
    };
  }
  const heldLabel = v.durationMs ? `Held ${formatHeldMinutes(v.durationMs)}` : 'Held';
  if (!v.recorded) {
    return { text: `${heldLabel} · not recorded`, tone: 'info', title: titleParts.join(' · ') };
  }
  if (opts.external === true) {
    return {
      text: `${heldLabel} · recorded elsewhere — not importable here`,
      tone: 'warn',
      title: `${titleParts.join(' · ')} · the organizer's tenant owns the recording`,
    };
  }
  if (opts.external === false) {
    return {
      text: `${heldLabel} · recording still processing`,
      tone: 'warn',
      title: `${titleParts.join(' · ')} · Microsoft hasn't listed the recording for us yet — Check… asks again`,
    };
  }
  return {
    text: `${heldLabel} · recorded — not importable here yet`,
    tone: 'warn',
    title: titleParts.join(' · '),
  };
}
