/**
 * Where each video of a stop-restart Meet recording starts on the MEETING
 * timeline.
 *
 * Meet writes one Drive file per run of the recording. The first one is the
 * primary (`local_audio_path`, "Video 1") and is also what AssemblyAI heard,
 * so AAI's t=0 is the meeting's t=0; the extra files live in
 * `gmeet_context.videoParts` and are played through `/audio?part=N`
 * (N = index + 2). Each part's offset is therefore plain wall-clock
 * arithmetic: `part.startTime − anchor`.
 *
 * This module is the ONE place that arithmetic lives. The detail page has
 * carried its own copy since the multi-video ship (2026-08-11); the
 * recordings backfill needs the identical number to write
 * `recording_media.offset_ms`, and two copies of a timeline calculation is
 * how a player and a transcript quietly disagree. Pure and client-safe on
 * purpose — no `server-only`, no db, no fs.
 */

import type { GmeetContext } from '@/lib/format';

/**
 * Wall clock of the meeting's t=0, in epoch ms, or null when the row has no
 * usable anchor (offsets are then unknowable and every part is treated as
 * starting at 0 by the caller).
 *
 * Preference order, unchanged from the detail page: the Meet API snapshot's
 * explicit anchor, else the start time of the recording whose Drive file IS
 * the primary, else the first recording Meet listed.
 */
export function partAnchorMs(gmeetContext: GmeetContext | null | undefined): number | null {
  const g = gmeetContext;
  const iso =
    g?.actuals?.anchorIso ??
    g?.actuals?.recordings?.find((r) => r.fileId && r.fileId === g?.videoFileId)?.startTime ??
    g?.actuals?.recordings?.[0]?.startTime;
  const ms = iso ? Date.parse(iso) : NaN;
  return Number.isNaN(ms) ? null : ms;
}

/** One extra Meet video placed on the meeting timeline. */
export interface VideoPartOffset {
  /** `?part=N` — the primary is 1, so videoParts[i] is i + 2. */
  partNo: number;
  /** undefined = the bytes are not on the VM (not fetched, or still being
   * generated by Google). */
  filename: string | undefined;
  /** Seconds from the meeting's t=0; null when the row has no anchor or the
   * part has no startTime. */
  offsetSec: number | null;
  /** Seconds, from the part's own start/end; null when either is missing. */
  durationSec: number | null;
}

/** Same, narrowed to the parts whose bytes we hold. */
export interface StoredVideoPart extends VideoPartOffset {
  filename: string;
}

/**
 * Every extra Meet video of the row, in capture order, with its offset.
 *
 * Numbering is by ARRAY INDEX and never re-flows: `/audio?part=N` looks the
 * part up as `videoParts[N-2]`, so a part whose bytes land later keeps the
 * number it always had.
 */
export function videoPartOffsets(
  gmeetContext: GmeetContext | null | undefined
): VideoPartOffset[] {
  const anchor = partAnchorMs(gmeetContext);
  return (gmeetContext?.videoParts ?? []).map((p, i) => {
    const startMs = p.startTime ? Date.parse(p.startTime) : NaN;
    const endMs = p.endTime ? Date.parse(p.endTime) : NaN;
    return {
      partNo: i + 2,
      filename: p.filename,
      offsetSec: anchor != null && !Number.isNaN(startMs) ? (startMs - anchor) / 1000 : null,
      durationSec:
        !Number.isNaN(startMs) && !Number.isNaN(endMs) ? (endMs - startMs) / 1000 : null,
    };
  });
}

/** The stored (downloaded) extra videos — what the player may actually offer. */
export function storedVideoParts(gmeetContext: GmeetContext | null | undefined): StoredVideoPart[] {
  return videoPartOffsets(gmeetContext).filter((p): p is StoredVideoPart => !!p.filename);
}

/**
 * Which video plays a given MEETING-time position, and where inside it.
 *
 * The primary covers everything before the first part that starts at or
 * before `seconds`; ties go to the later-starting part (a part with
 * `offsetSec` 0 never steals from the primary, which is what makes an
 * un-anchored row behave like a single video).
 */
export function partForMeetingTime(
  parts: StoredVideoPart[],
  seconds: number
): { partNo: number; offsetSec: number; localSec: number } {
  let partNo = 1;
  let offsetSec = 0;
  for (const p of parts) {
    if (p.offsetSec != null && seconds >= p.offsetSec && p.offsetSec > offsetSec) {
      partNo = p.partNo;
      offsetSec = p.offsetSec;
    }
  }
  return { partNo, offsetSec, localSec: Math.max(0, seconds - offsetSec) };
}
