-- Dedicated speaker-identification AI pass, run at completion BEFORE any
-- summary exists. Consolidates voiceprint hints + transcript text + video
-- frames (Meet name tiles) into speaker suggestions, then the app waits for
-- a human to review/finalize labels before the quick summary is generated
-- (notes are no longer auto-generated by the sweeper).

SET search_path = meeting_whisperer_prod, public;

ALTER TABLE transcripts ADD COLUMN IF NOT EXISTS speaker_id_status text;
ALTER TABLE transcripts ADD COLUMN IF NOT EXISTS speaker_id_error text;
ALTER TABLE transcripts ADD COLUMN IF NOT EXISTS speaker_id_at timestamptz;
