'use client';

import { Zap } from 'lucide-react';
import type { GmeetContext } from '@/lib/format';
import { autoMarkerOf, reportLabel } from '@/lib/auto-marker';

/**
 * One line on the transcript page answering "why is this here and what is
 * automation doing with it": which sweep imported it (series / account),
 * under whose connection, which report kind was resolved, whether the
 * speaker gate passed, and who was told. Rendered from the row's automation
 * marker (lib/auto-marker) — nothing for hand imports / uploads.
 */
export function AutoProvenance({
  ctx,
  generated,
  onOpenSeries,
}: {
  ctx: GmeetContext | null | undefined;
  /** Notes or a report exist on the row — a held gate was cleared by hand. */
  generated?: boolean;
  onOpenSeries?: (seriesId: number) => void;
}) {
  const m = autoMarkerOf(ctx);
  if (!m) return null;
  const review = ctx?.autoReview ?? null;
  const held = !!review && !review.passed && !generated;
  const report = ctx?.uploadPrefs?.report ?? 'summary';
  const audience = [m.byEmail, ...m.watchers].map((e) => e.split('@')[0]).join(', ');

  const via =
    m.source === 'series' ? (
      <>
        series{' '}
        {onOpenSeries && m.seriesId ? (
          <button
            type="button"
            className="underline decoration-dotted underline-offset-2 hover:text-foreground"
            onClick={() => onOpenSeries(m.seriesId!)}
          >
            {m.seriesTitle ?? `#${m.seriesId}`}
          </button>
        ) : (
          <span>{m.seriesTitle ?? `#${m.seriesId}`}</span>
        )}
      </>
    ) : (
      <>account auto-sync</>
    );

  const gate = !review
    ? generated
      ? 'generated by hand'
      : 'speaker check pending'
    : review.passed
      ? `speakers auto-confirmed → ${review.generated ? reportLabel(review.generated) : 'nothing generated'}`
      : generated
        ? 'speaker gate held, then reviewed by hand'
        : `speakers need review${review.reason ? ` (${review.reason})` : ''}`;

  return (
    <span
      className="inline-flex max-w-full flex-wrap items-center gap-x-1 rounded-md border border-primary/20 bg-primary/5 px-1.5 py-0.5 text-[11px] text-muted-foreground"
      title={`Auto-imported via ${m.source === 'series' ? `series "${m.seriesTitle ?? m.seriesId}"` : 'account auto-sync'} under ${m.byEmail}'s connection at ${new Date(m.at).toLocaleString()}. Report kind resolved for everyone served: ${reportLabel(report)}. ${review ? (review.passed ? 'Speaker gate passed unattended.' : `Speaker gate held: ${review.reason ?? 'low confidence'} — the review DM went to ${audience}.`) : 'Speaker gate not evaluated yet.'}`}
    >
      <Zap className="h-3 w-3 shrink-0 text-primary" />
      <span>
        Auto-imported via {via} as {m.byEmail.split('@')[0]}
      </span>
      <span>· {reportLabel(report)}</span>
      <span className={held ? 'text-amber-600 dark:text-amber-400' : ''}>· {gate}</span>
      {m.watchers.length > 0 && <span>· for {audience}</span>}
    </span>
  );
}
